version: 0.7.0.{build}
image: Visual Studio 2017
clone_folder: c:\naev
install:
- ps: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libpng mingw-w64-x86_64-openal mingw-w64-x86_64-libvorbis mingw-w64-x86_64-freetype mingw-w64-x86_64-libzip 2>&1"
build_script:
- cmd: >-
    SET MSYSTEM=MINGW64

    C:\msys64\usr\bin\bash -lc "env"

    C:\msys64\usr\bin\bash -lc "cd /c/naev; ./autogen.sh 2>&1"

    C:\msys64\usr\bin\bash -lc "cd /c/naev; ./configure"

    C:\msys64\usr\bin\bash -lc "cd /c/naev; make"
