.TH NAEV 6 "2009" "NAEV" "NAEV"
.
.SH NAME
Naev \- A 2D space trading and combat game.
.
.SH SYNOPSIS
.
.B naev
[\fIOPTIONS\fR]
[\fIDATA\fR]
.
.SH DESCRIPTION
.
.B NAEV
is a space trading and combat game, inspired by Escape Velocity.

Played from a top-down perspective with isometric sprites, the player
is free to explore the galaxy as they see fit, trading or pirating
their way to a vast fortune.

Naev is set in a futuristic science fiction environment, in which
the player finds himself in the wake of a massive galactic cataclysm
which erupted from the Sol system and destroyed everything within
tens of lightyears, resulting in a massive, volatile nebula.
.
.SH OPTIONS
.
.TP
.BI -F,\ --fps \ number
limits frames per second
.TP
.B -f, --fullscreen
runs the game in full screen mode
.TP
.B -G, --generate
regenerates the nebula images (Slow)
.TP
.BI -H \ number
sets the window height to \fInumber\fP
.TP
.B -h, --help
display a help message and exit
.TP
.BI -J,\ --Joystick \ string
use joystick whose name contains \fIstring\fP
.TP
.BI -j,\ --joystick \ number
use joystick \fInumber\fP
.TP
.B --M, --mute
disables sound
.TP
.B -S, --sound
forcibly enables sound
.TP
.BI -m,\ --mvol \ number
sets the music volume to \fInumber\fP
.TP
.BI -s,\ --svol \ number
sets the sound volume to \fInumber\fP
.TP
.B -V, --vsync
limits frames per second to screen refresh rate
.TP
.B -v, --version
prints the version and exits
.TP
.BI -W \ number
sets the window width to \fInumber\fP

.SH AUTHOR
.
Written by Edgar Simo <bobbens@gmail.com>.
.br
Major contributions by Nikola Whallon <6.saturn.6@gmail.com>, Josiah
Schwartfeger, and Sean Hildebrand <silverwraithii@gmail.com>.

An exhaustive list of contributors can be found at:
.br
http://github.com/bobbens/naev/blob/master/AUTHORS.

This manual page was originally written by Sean Hildebrand.
.br
Visit the official homepage: http://code.google.com/p/naev/
