.TH NAEV 6 "2009" "NAEV" "NAEV"
.
.SH NAME
Naev \- A 2D space trading and combat game.
.
.SH SYNOPSIS
.
.B naev
[\fIOPTIONS\fR]
[\fIDATA\fR]
.
.SH DESCRIPTION
.
.B Naev
is a space trading and combat game, inspired by Escape Velocity.

Played from a top-down perspective with isometric sprites, the player
is free to explore the galaxy as they see fit, trading or pirating
their way to a vast fortune.

Naev is set in a futuristic science fiction environment, in which
the player finds himself in the wake of a massive galactic cataclysm
which erupted from the Sol system and destroyed everything within
tens of light years, resulting in a massive, volatile nebula.
.
.SH OPTIONS
.
.TP
.BI -d,\ --datapath \ dir
Specifies a custom path for all user data (saves, screenshots, etc.)
.TP
.BI --devmode
Enables the universe editor (accessible via main menu).
.TP
.BI --devcsv
Generates CSV output from ndata for development purposes.
.TP
.BI -F,\ --fps \ number
Limits frames per second to \fInumber\fP
.TP
.B -f, --fullscreen
Runs the game in full-screen mode
.TP
.B -G, --generate
Regenerates the nebula images (slow)
.TP
.BI -H \ number
Sets the window height to \fInumber\fP
.TP
.B -h, --help
Display a help message and exit
.TP
.BI -J,\ --Joystick \ string
Use joystick whose name contains \fIstring\fP
.TP
.BI -j,\ --joystick \ number
Use joystick \fInumber\fP
.TP
.B -M, --mute
Disables sound
.TP
.BI -m,\ --mvol \ number
Sets the music volume to \fInumber\fP
.TP
.B -S, --sound
Forcibly enables sound
.TP
.BI -s,\ --svol \ number
Sets the sound volume to \fInumber\fP
.TP
.B -V, --vsync
Limits frames per second to screen refresh rate
.TP
.B -v, --version
Prints the version and exits
.TP
.BI -W \ number
Sets the window width to \fInumber\fP

.SH BUGS
.
Bugs and feature requests can be filed at:

https://github.com/naev/naev/issues/
.PP

.SH AUTHOR
.
Originally written by Edgar Simo <bobbens@gmail.com>. Currently
developed by the Naev Team.
.br
An exhaustive list of contributors can be found at:
.br
http://github.com/naev/naev/blob/master/AUTHORS.

.br
Visit the official homepage: http://naev.org/
