#!/bin/bash
set -euo pipefail
set -x

conv() {
	cwebp -z 9 "$1" -o ../artwork/"${1/.png/.webp}"
	git -C ../artwork add "${1/.png/.webp}"
	git rm "$1"
}

conv gfx/portraits/dvaered/unique/vicious.png
conv gfx/portraits/dvaered/unique/zolo.png
conv gfx/portraits/dvaered/unique/ka\'def.png
conv gfx/portraits/dvaered/dv_civilian_f1.png
conv gfx/portraits/dvaered/dv_civilian_f10.png
conv gfx/portraits/dvaered/dv_civilian_f11.png
conv gfx/portraits/dvaered/dv_civilian_f2.png
conv gfx/portraits/dvaered/dv_civilian_f3.png
conv gfx/portraits/dvaered/dv_civilian_f4.png
conv gfx/portraits/dvaered/dv_civilian_f5.png
conv gfx/portraits/dvaered/dv_civilian_f6.png
conv gfx/portraits/dvaered/dv_civilian_f7.png
conv gfx/portraits/dvaered/dv_civilian_f8.png
conv gfx/portraits/dvaered/dv_civilian_f9.png
conv gfx/portraits/dvaered/dv_civilian_m1.png
conv gfx/portraits/dvaered/dv_civilian_m10.png
conv gfx/portraits/dvaered/dv_civilian_m11.png
conv gfx/portraits/dvaered/dv_civilian_m2.png
conv gfx/portraits/dvaered/dv_civilian_m3.png
conv gfx/portraits/dvaered/dv_civilian_m4.png
conv gfx/portraits/dvaered/dv_civilian_m5.png
conv gfx/portraits/dvaered/dv_civilian_m6.png
conv gfx/portraits/dvaered/dv_civilian_m7.png
conv gfx/portraits/dvaered/dv_civilian_m8.png
conv gfx/portraits/dvaered/dv_civilian_m9.png
conv gfx/portraits/dvaered/dv_general1.png
conv gfx/portraits/dvaered/dv_military_f1.png
conv gfx/portraits/dvaered/dv_military_f2.png
conv gfx/portraits/dvaered/dv_military_f3.png
conv gfx/portraits/dvaered/dv_military_f4.png
conv gfx/portraits/dvaered/dv_military_f5.png
conv gfx/portraits/dvaered/dv_military_f6.png
conv gfx/portraits/dvaered/dv_military_f7.png
conv gfx/portraits/dvaered/dv_military_f8.png
conv gfx/portraits/dvaered/dv_military_m1.png
conv gfx/portraits/dvaered/dv_military_m2.png
conv gfx/portraits/dvaered/dv_military_m3.png
conv gfx/portraits/dvaered/dv_military_m4.png
conv gfx/portraits/dvaered/dv_military_m5.png
conv gfx/portraits/dvaered/dv_military_m6.png
conv gfx/portraits/dvaered/dv_military_m7.png
conv gfx/portraits/dvaered/dv_military_m8.png
conv gfx/portraits/empire/unique/czesc.png
conv gfx/portraits/empire/unique/dimitri.png
conv gfx/portraits/empire/unique/keer.png
conv gfx/portraits/empire/unique/soldner.png
conv gfx/portraits/empire/empire_mil_f1.png
conv gfx/portraits/empire/empire_mil_f2.png
conv gfx/portraits/empire/empire_mil_f3.png
conv gfx/portraits/empire/empire_mil_f4.png
conv gfx/portraits/empire/empire_mil_f5.png
conv gfx/portraits/empire/empire_mil_m1.png
conv gfx/portraits/empire/empire_mil_m2.png
conv gfx/portraits/empire/empire_mil_m3.png
conv gfx/portraits/empire/empire_mil_m4.png
conv gfx/portraits/empire/empire_mil_m5.png
conv gfx/portraits/empire/empire_mil_m6.png
conv gfx/portraits/empire/empire_mil_m7.png
conv gfx/portraits/empire/empire_mil_m8.png
conv gfx/portraits/flf/unique/benito.png
conv gfx/portraits/neutral/unique/aristocrat.png
conv gfx/portraits/neutral/unique/arnoldsmith.png
conv gfx/portraits/neutral/unique/cynthia.png
conv gfx/portraits/neutral/unique/cynthia_father.png
conv gfx/portraits/neutral/unique/dealer.png
conv gfx/portraits/neutral/unique/drunkard.png
conv gfx/portraits/neutral/unique/fakesister.png
conv gfx/portraits/neutral/unique/flintley.png
conv gfx/portraits/neutral/unique/hunter.png
conv gfx/portraits/neutral/unique/jorek.png
conv gfx/portraits/neutral/unique/laidback.png
conv gfx/portraits/neutral/unique/mia.png
conv gfx/portraits/neutral/unique/michal.png
conv gfx/portraits/neutral/unique/middleaged.png
conv gfx/portraits/neutral/unique/neil.png
conv gfx/portraits/neutral/unique/nexus_agent.png
conv gfx/portraits/neutral/unique/oldwoman.png
conv gfx/portraits/neutral/unique/paddy.png
conv gfx/portraits/neutral/unique/rebina.png
conv gfx/portraits/neutral/unique/rebina_casual.png
conv gfx/portraits/neutral/unique/reynir.png
conv gfx/portraits/neutral/unique/reynir2.png
conv gfx/portraits/neutral/unique/shifty_merchant.png
conv gfx/portraits/neutral/unique/unfamiliarman.png
conv gfx/portraits/neutral/unique/youngbusinessman.png
conv gfx/portraits/neutral/unique/youngbusinessman2.png
conv gfx/portraits/neutral/barman.png
conv gfx/portraits/neutral/cyborg1.png
conv gfx/portraits/neutral/cyborg2.png
conv gfx/portraits/neutral/cyborg3.png
conv gfx/portraits/neutral/female1.png
conv gfx/portraits/neutral/female10.png
conv gfx/portraits/neutral/female11.png
conv gfx/portraits/neutral/female12.png
conv gfx/portraits/neutral/female13.png
conv gfx/portraits/neutral/female2.png
conv gfx/portraits/neutral/female3.png
conv gfx/portraits/neutral/female4.png
conv gfx/portraits/neutral/female5.png
conv gfx/portraits/neutral/female6.png
conv gfx/portraits/neutral/female7.png
conv gfx/portraits/neutral/female8.png
conv gfx/portraits/neutral/female9.png
conv gfx/portraits/neutral/male1.png
conv gfx/portraits/neutral/male10.png
conv gfx/portraits/neutral/male11.png
conv gfx/portraits/neutral/male12.png
conv gfx/portraits/neutral/male13.png
conv gfx/portraits/neutral/male2.png
conv gfx/portraits/neutral/male3.png
conv gfx/portraits/neutral/male4.png
conv gfx/portraits/neutral/male5.png
conv gfx/portraits/neutral/male6.png
conv gfx/portraits/neutral/male7.png
conv gfx/portraits/neutral/male8.png
conv gfx/portraits/neutral/male9.png
conv gfx/portraits/neutral/miner1.png
conv gfx/portraits/neutral/miner2.png
conv gfx/portraits/neutral/scientist.png
conv gfx/portraits/neutral/scientist2.png
conv gfx/portraits/neutral/scientist3.png
conv gfx/portraits/neutral/thief1.png
conv gfx/portraits/neutral/thief2.png
conv gfx/portraits/neutral/thief3.png
conv gfx/portraits/neutral/thief4.png
conv gfx/portraits/pirate/pirate1.png
conv gfx/portraits/pirate/pirate10.png
conv gfx/portraits/pirate/pirate11.png
conv gfx/portraits/pirate/pirate13.png
conv gfx/portraits/pirate/pirate14.png
conv gfx/portraits/pirate/pirate2.png
conv gfx/portraits/pirate/pirate3.png
conv gfx/portraits/pirate/pirate4.png
conv gfx/portraits/pirate/pirate5.png
conv gfx/portraits/pirate/pirate6.png
conv gfx/portraits/pirate/pirate7.png
conv gfx/portraits/pirate/pirate8.png
conv gfx/portraits/pirate/pirate9.png
conv gfx/portraits/pirate/pirate_militia1.png
conv gfx/portraits/pirate/pirate_militia2.png
conv gfx/portraits/pirate/pirate12.png
conv gfx/portraits/sirius/unique/draga.png
conv gfx/portraits/sirius/unique/harja.png
conv gfx/portraits/sirius/unique/joanne.png
conv gfx/portraits/sirius/unique/patrek.png
conv gfx/portraits/sirius/unique/rodentman.png
conv gfx/portraits/sirius/unique/shaman.png
conv gfx/portraits/sirius/unique/strangeman.png
conv gfx/portraits/sirius/sirius_fyrra_f1.png
conv gfx/portraits/sirius/sirius_fyrra_f2.png
conv gfx/portraits/sirius/sirius_fyrra_f3.png
conv gfx/portraits/sirius/sirius_fyrra_f4.png
conv gfx/portraits/sirius/sirius_fyrra_f5.png
conv gfx/portraits/sirius/sirius_fyrra_m1.png
conv gfx/portraits/sirius/sirius_fyrra_m2.png
conv gfx/portraits/sirius/sirius_fyrra_m3.png
conv gfx/portraits/sirius/sirius_fyrra_m4.png
conv gfx/portraits/sirius/sirius_fyrra_m5.png
conv gfx/portraits/sirius/sirius_shiara_f1.png
conv gfx/portraits/sirius/sirius_shiara_f2.png
conv gfx/portraits/sirius/sirius_shiara_f3.png
conv gfx/portraits/sirius/sirius_shiara_f4.png
conv gfx/portraits/sirius/sirius_shiara_f5.png
conv gfx/portraits/sirius/sirius_shiara_m1.png
conv gfx/portraits/sirius/sirius_shiara_m2.png
conv gfx/portraits/sirius/sirius_shiara_m3.png
conv gfx/portraits/sirius/sirius_shiara_m4.png
conv gfx/portraits/sirius/sirius_shiara_m5.png
conv gfx/portraits/none.png
conv gfx/portraits/soromid/unique/chelsea.png
conv gfx/portraits/unknown.png
conv gfx/portraits/zalek/unique/geller.png
conv gfx/portraits/zalek/unique/logan.png
conv gfx/portraits/zalek/unique/mensing.png
conv gfx/portraits/zalek/unique/student.png
