on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

name: Nightly Release

permissions: {}
jobs:
  "Package_Source":
    runs-on: naev-release
    steps:
      - name: Checkout Naev Repository
        uses: actions/checkout@v4
        with:
          path: source
          fetch-depth: 0
          submodules: true

      - name: Package Dist
        run: |
          meson setup build source -Dexecutable=disabled -Ddocs_c=disabled -Ddocs_lua=disabled --wrap-mode=forcefallback
          meson dist -C build --no-tests --include-subprojects

      - name: Collect Artifacts
        run: |
          mkdir -p build/dist
          cp -r source/utils/ci/itch source/utils/ci/steam source/utils/ci/berg build/dist/
          cp source/utils/buildAppImage.sh build/dist
          cp source/utils/buildUniversalBundle.sh build/dist
          cp -r source/extras/macos/dmg_assets build/dist
          cp source/extras/macos/entitlements.plist build/dist
          mv build/meson-dist/naev-*.tar.xz build/dist/source.tar.xz
          cp source/dat/VERSION build/dist

      - name: Upload Source Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-dist
          path: ${{ github.workspace }}/build/dist/source.tar.xz
          if-no-files-found: error

      - name: Upload Version Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-version
          path: ${{ github.workspace }}/build/dist/VERSION
          if-no-files-found: error

      - name: Upload AppImage Packaging Script Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-appimage-packaging
          path: ${{ github.workspace }}/build/dist/buildAppImage.sh
          if-no-files-found: error

      - name: Upload Universal Bundle Packaging Script Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-macos-packaging
          path: ${{ github.workspace }}/build/dist/buildUniversalBundle.sh
          if-no-files-found: error

      - name: Upload DMG Assets Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-macos-dmg
          path: ${{ github.workspace }}/build/dist/dmg_assets
          if-no-files-found: error
          include-hidden-files: true

      - name: Upload Entitlements PLIST Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-macos-entitlements
          path: ${{ github.workspace }}/build/dist/entitlements.plist
          if-no-files-found: error

      - name: Upload Codeberg Deployment Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-codeberg-deployment
          path: ${{ github.workspace }}/build/dist/berg/*
          if-no-files-found: error

      - name: Upload Steam Deployment Script Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-steam-deployment
          path: ${{ github.workspace }}/build/dist/steam/*
          if-no-files-found: error

      - name: Upload Itch Deployment Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-itch-deployment
          path: ${{ github.workspace }}/build/dist/itch/*
          if-no-files-found: error
          include-hidden-files: true

  "Linux_Naev_Release":
    needs: "Package_Source"
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: naev-steamruntime
            config: linux_steamruntime.ini
            wrap_mode: default
            target: x86_64-unknown-linux-gnu
    
    runs-on: ${{ matrix.image }}

    steps:
      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: naev-dist

      - name: Extract Source
        run: |
          mkdir source
          tar -xf source.tar.xz -C source --strip 1

      - name: Meson Setup
        run: |
          meson setup build source \
              --native-file='source/utils/build/linux_steamruntime.ini' \
              --buildtype=debug \
              --wrap-mode=${{ matrix.wrap_mode }} \
              --force-fallback-for=sdl2_image,glpk,SuiteSparse \
              -Dsteamruntime=true \
              -Dprefix="/usr" \
              -Dinstaller=true \
              -Db_lto=true \
              -Dauto_features=enabled \
              -Ddocs_c=disabled \
              -Ddocs_lua=disabled

      - name: Meson Compile
        run: |
          meson compile -C build

      - name: Meson Install
        run: |
          meson install -C build
        env:
          DESTDIR: ${{ github.workspace }}/staging

      - name: Compile AppImage
        run: |
              ./source/utils/buildAppImage.sh -d -n -s source -b build

      - name: Collect Steam Linux64 Artifacts
        run: |
          mkdir -p build/dist/

          mv staging/usr/bin/naev build/dist/naev.x64
          chmod +x build/dist/naev.x64

          tar -cJvf build/dist/naev-appdir.tar.xz -C  build/dist/ AppDir

          tar -cJvf build/dist/naev-ndata.tar.xz -C staging/usr/share/naev dat

      - name: Upload Naev Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-steamruntime
          path: ${{ github.workspace }}/build/dist/naev.x64

      - name: Upload Naev Data Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-ndata
          path: ${{ github.workspace }}/build/dist/naev-ndata.tar.xz

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-linux-appdir-x86-64
          path: "${{ github.workspace }}/build/dist/naev-appdir.tar.xz"

  "Linux_Package_Release":
    needs:
      [
        Package_Source,
        Linux_Naev_Release
      ]
    runs-on: naev-release
    steps:
      - name: Get AppImage Packaging Script
        uses: actions/download-artifact@v3
        with:
          name: naev-appimage-packaging

      - name: Get AppDir
        uses: actions/download-artifact@v3
        with:
          name: naev-linux-appdir-x86-64

      - name: Package AppImage
        run: |
              chmod +x buildAppImage.sh
              tar -Jxf naev-appdir.tar.xz
              ./buildAppImage.sh -d -n -p -a "./AppDir" -b build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-linux-x86-64
          path: "${{ github.workspace }}/build/dist/*"

  "Windows_Naev_Release":
    needs: "Package_Source"

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: naev-windows
            config: windows_cross_mingw.ini
            target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.image }}
    env:
      PKG_CONFIG: "x86_64-w64-mingw32-pkg-config"
      PKG_CONFIG_PATH: "/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig:/__w/naev/naev/source/subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/etc"
      BINDGEN_EXTRA_CLANG_ARGS: "--sysroot=/usr/x86_64-w64-mingw32/sys-root/mingw --target=x86_64-w64-mingw32"

    steps:
      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: naev-dist

      - name: Extract Source
        run: |
          mkdir source
          tar -xf source.tar.xz -C source --strip 1

      - name: Meson Setup
        # We disable b_lto here because it messes with backtraces on windows
        run: |
          meson setup build source \
              --prefix="$(pwd)"/source/extras/windows/installer \
              --bindir=. \
              -Dndata_path=. \
              --cross-file='source/utils/build/${{ matrix.config }}' \
              --native-file='source/utils/build/linux.ini' \
              --buildtype=debug \
              --wrap-mode=nopromote \
              -Dinstaller=true \
              -Drelease=true \
              -Db_lto=false \
              -Dauto_features=enabled \
              -Ddocs_c=disabled \
              -Ddocs_lua=disabled

      - name: Meson Compile
        run: |
          meson compile -C build

      - name: Meson Install
        run: |
          meson install -C build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: naev-win64
          path: ${{ github.workspace }}/build/dist/*
          if-no-files-found: error

  "Darwin_Compile_Naev":
    needs: "Package_Source"

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: naev-macos
            arch: x86_64
            deploymenttarget: "11.0"
            config: macos_cross_osxcross.ini
          - image: naev-macos
            arch: aarch64
            deploymenttarget: "13.0"
            config: macos_aarch64_cross_osxcross.ini

    runs-on: ${{ matrix.image }}
    env:
      BUILDARCH: "${{ matrix.arch }}"
      HOST: "${{ matrix.arch }}-apple-darwin23"
      MACOSX_DEPLOYMENT_TARGET: "${{ matrix.deploymenttarget }}"
      PKG_CONFIG: "${{ matrix.arch }}-apple-darwin23-pkg-config"
      PKG_CONFIG_PATH: "/usr/lib/osxcross/macports/pkgs/opt/local/lib/pkgconfig"
      BINDGEN_EXTRA_CLANG_ARGS: "--sysroot=/usr/lib/osxcross/SDK/MacOSX14.sdk --target=${{ matrix.arch }}-apple-darwin"

    steps:
      - name: Configure Build Environment
        run: |
          /usr/bin/setup-devenv.sh

      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: naev-dist

      - name: Extract Source
        run: |
          mkdir source
          tar -xf source.tar.xz -C source --strip 1

      - name: Meson Setup
        run: |
          meson setup build source \
              --prefix="$(pwd)"/build/macos/Naev.app \
              --bindir=Contents/MacOS \
              --libdir=Contents/Frameworks \
              -Dndata_path=Contents/Resources \
              --cross-file='source/utils/build/${{ matrix.config }}' \
              --native-file='source/utils/build/linux.ini' \
              --buildtype=debug \
              -Dinstaller=false \
              -Drelease=true \
              -Db_lto=true \
              -Dauto_features=enabled \
              -Ddocs_c=disabled \
              -Ddocs_lua=disabled

      - name: Meson Compile
        run: |
          meson compile -C build

      - name: Meson Install
        run: |
          meson install -C build

      - name: Fix zip name
        run: |
          mv build/dist/naev-macos.zip build/dist/naev-macos-${{ matrix.arch }}.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: naev-macos-${{ matrix.arch }}
          path: ${{ github.workspace }}/build/dist/naev-macos-${{ matrix.arch }}.zip
          if-no-files-found: error

  "Darwin_Package_Release":
    needs:
      [
        Package_Source,
        Darwin_Compile_Naev
      ]
    runs-on: naev-macos

    steps:
      - name: Get Universal Bundle Packaging Script
        uses: actions/download-artifact@v3
        with:
          name: naev-macos-packaging

      - name: Get DMG Assets
        uses: actions/download-artifact@v3
        with:
          name: naev-macos-dmg
          path: dmg_assets

      - name: Get Entitlements PLIST
        uses: actions/download-artifact@v3
        with:
          name: naev-macos-entitlements

      - name: Get x86_64 macOS Bundle
        uses: actions/download-artifact@v3
        with:
          name: naev-macos-x86_64

      - name: Get ARM64 macOS Bundle
        uses: actions/download-artifact@v3
        with:
          name: naev-macos-aarch64

      - name: Package Universal Bundle
        run: |
              mkdir -p arm64 x86_64
              chmod +x buildUniversalBundle.sh
              unzip naev-macos-aarch64.zip -d arm64
              unzip naev-macos-x86_64.zip -d x86_64
              ./buildUniversalBundle.sh -d -i ./dmg_assets -e ./entitlements.plist -a ./arm64 -x ./x86_64 -b ./build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-macos
          path: "${{ github.workspace }}/build/dist/*"

  "Upload_Naev_Release":
    strategy:
      fail-fast: false
      matrix:
        include:
          - releasetype: codeberg
          - releasetype: steam
          - releasetype: itch

    runs-on: naev-release
    needs:
      [
        Package_Source,
        Linux_Package_Release,
        Windows_Naev_Release,
        Darwin_Package_Release,
      ]
    if: ${{ github.repository == 'naev/naev' }}

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/build/staging

      - name: Checkout Naev Repository
        if: ${{ matrix.releasetype == 'codeberg' }}
        uses: actions/checkout@v4
        with:
          path: build/staging/repo

      - name: Generate Nightly Changelog
        if: ${{ matrix.releasetype == 'codeberg' }}
        working-directory: ${{ github.workspace }}/build/staging/repo
        run: |
          # Get last nightly tag commit (if exists)
          if git rev-parse nightly >/dev/null 2>&1; then
            last_tag="nightly"
          else
            last_tag="$(git rev-list --max-parents=0 HEAD)" # fallback: first commit
          fi

          # Repo URL base for commit links
          repo_url="https://codeberg.org/naev/naev/commit"

          # Build date and sha
          build_date="$(date +%Y-%m-%d)"
          build_sha="$(git rev-parse HEAD)"

          # Generate and changelog into RELEASE_NOTES env var
          {
            echo "RELEASE_NOTES<<EOF"
            echo "## Built on ${build_date} Git SHA: [${build_sha:0:7}](${repo_url}/${build_sha})"
            echo ""
            echo "This is an automated development snapshot build. Debugging is enabled."
            echo ""
            echo "Please report any issues you run into on the [issue tracker](https://codeberg.org/naev/naev/issues)!"
            echo ""
            echo "### Changes since last build"
            echo ""
            git log --pretty=format:"- %s ([%h](${repo_url}/%H))" ${last_tag}..HEAD
            echo "EOF"
          } >> $GITHUB_ENV

          # Generate release title into RELEASE_TITLE env var
          echo "RELEASE_TITLE=Nightly Release (${build_date}, ${build_sha:0:7})" >> $GITHUB_ENV

      - name: Push 'nightly' tag
        if: ${{ matrix.releasetype == 'codeberg' }}
        working-directory: ${{ github.workspace }}/build/staging/repo
        run: |
          git config --local user.email "naevBuilder@emoss.ca"
          git config --local user.name "Naev Runner [bot]"
          git tag -f nightly
          git push --force origin nightly

      - name: Stage Codeberg Release
        if: ${{ matrix.releasetype == 'codeberg' }}
        run: |
          chmod -R +x build/staging/naev-codeberg-deployment
          cp -r build/staging/naev-codeberg-deployment/* "$(pwd)"
          ./BergDeploy.sh -n -t "$(pwd)/build/staging" -o "$(pwd)/build/dist" -r "nightly"

      - name: Upload Codeberg Release
        if: ${{ matrix.releasetype == 'codeberg' }}
        uses: actions/forgejo-release@v2.7.2
        with:
          direction: upload
          release-dir: "$(pwd)/build/dist"
          release-notes: "${{ env.RELEASE_NOTES }}"
          override: true
          prerelease: true
          hide-archive-link: true
          tag: nightly
          title: ${{ env.RELEASE_TITLE }}

      - name: Build and Upload itch.io Release
        if: ${{ matrix.releasetype == 'itch' }}
        run: |
          chmod -R +x build/staging/naev-itch-deployment
          cp -r build/staging/naev-itch-deployment/* "$(pwd)"
          ./ItchDeploy.sh -n -t "$(pwd)/build/staging" -o "$(pwd)/build/dist"
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

      - name: Build and Upload Steam Release
        if: ${{ matrix.releasetype == 'steam' }}
        run: |
          chmod -R +x build/staging/naev-steam-deployment
          cp -r build/staging/naev-steam-deployment/* "$(pwd)"
          ./SteamDeploy.sh -n -t "$(pwd)/build/staging" -o "$(pwd)/build/dist"
        env:
          STEAMCMD_USER: ${{ secrets.STEAMCMD_USER }}
          STEAMCMD_PASS: ${{ secrets.STEAMCMD_PASS }}
          TFA_IMAP: ${{ secrets.TFA_IMAP }}
          TFA_PASS: ${{ secrets.TFA_PASS }}
          TFA_USER: ${{ secrets.TFA_USER }}
