on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "nightly"
      - "v*.*.*"
      - "v*.*.*-alpha*"
      - "v*.*.*-beta*"
      - "v*.*.*-rc*"

name: CI

jobs:
  "Package_Source":
    runs-on: naev-release
    steps:
      - name: Force Codeberg over SSH
        run: git config --global url."ssh://git@codeberg.org/naev/".insteadOf https://codeberg.org/naev/

      - name: Checkout Naev Repository
        uses: actions/checkout@v4
        with:
          lfs: false # defer LFS to after cache restore
          path: source
          submodules: true
          ssh-key: ${{ secrets.CODEBERG_SSH_KEY }}
          ssh-known-hosts: ${{ secrets.CODEBERG_SSH_KNOWN_HOSTS }}
          persist-credentials: true

      - name: Fetch Meson subprojects
        run: |
          mkdir -p source/subprojects/packagecache
          if find source/subprojects/packagecache -mindepth 1 -maxdepth 1 | read || find source/subprojects/packagefiles -mindepth 1 -maxdepth 1 | read; then
            echo "Using cached Meson subprojects/packagefiles; skip download"
          else
            meson subprojects download --sourcedir source
          fi

      - name: Capture assets submodule revision
        id: assets_rev
        run: echo "rev=$(git -C source submodule status assets | awk '{print $1}')" >> "$GITHUB_OUTPUT"

      - name: Restore LFS cache
        uses: actions/cache@v3
        with:
          path: |
            source/.git/lfs/objects
            source/.git/modules/assets/lfs/objects
          key: lfs-${{ runner.os }}-${{ steps.assets_rev.outputs.rev }}
          restore-keys: lfs-${{ runner.os }}-

      - name: Fetch and checkout LFS
        run: |
          git -C source/assets lfs fetch --all
          git -C source/assets lfs checkout

      - name: Package Dist
        run: |
          meson setup build source -Dexecutable=disabled -Ddocs_c=disabled -Ddocs_lua=disabled --wrap-mode=forcefallback
          meson dist -C build --no-tests --include-subprojects

      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naev-dist-${{ github.sha }}
          path: ${{ github.workspace }}/build/meson-dist/*

  "Linux_Compile_Naev":
    needs: "Package_Source"
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: naev-steamruntime
            config: linux_steamruntime.ini
            wrap_mode: default
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.image }}

    steps:
      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: naev-dist-${{ github.sha }}

      - name: Extract Source
        run: |
          mkdir source
          tar -xf naev-*.tar.xz -C source --strip 1

      - name: Cache Meson wrap downloads
        uses: actions/cache@v3
        with:
          path: source/subprojects/packagecache
          key: wrap-${{ matrix.image }}-${{ hashFiles('source/subprojects/*.wrap') }}
          restore-keys: wrap-${{ matrix.image }}-

      - name: Cache Cargo home
        uses: actions/cache@v3
        with:
          path: build/cargo-home
          key: cargo-${{ matrix.image }}-${{ matrix.target }}-${{ hashFiles('source/Cargo.toml.in', 'source/meson.build') }}
          restore-keys: |
            cargo-${{ matrix.image }}-${{ matrix.target }}-
            cargo-${{ matrix.image }}-

      - name: Meson Setup
        id: setup
        run: |
          meson setup build source \
              --native-file='source/utils/build/${{ matrix.config }}' \
              --buildtype=debug \
              --wrap-mode=${{ matrix.wrap_mode }} \
              --force-fallback-for=sdl2_image,glpk,SuiteSparse \
              -Dsteamruntime=false \
              -Dprefix="/usr" \
              -Db_lto=true \
              -Dinstaller=false \
              -Db_lto=true \
              -Dauto_features=enabled \
              -Ddocs_c=disabled \
              -Ddocs_lua=disabled

      - name: Upload Setup Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.setup.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}-${{ github.sha }}-setup-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

      - name: Meson Compile
        id: compile
        run: |
          meson compile -C build

      - name: Meson Test (luacheck)
        id: luacheck
        run: |
          meson test luacheck -C build

      - name: Upload Compile Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.compile.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}-${{ github.sha }}-compile-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

      - name: Upload Luacheck Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.luacheck.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}-${{ github.sha }}-luacheck-log
          path: ${{ github.workspace }}/build/meson-logs/testlog.txt

      - name: Test Install
        id: install
        run: |
          meson install -C build
        env:
          DESTDIR: "${{ github.workspace }}/staging"

      - name: Upload Install Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.install.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}-${{ github.sha }}-install-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

      - name: Cache Cargo home
        uses: actions/cache@v3
        with:
          path: appImageBuild/builddir/cargo-home
          key: cargo-appimage-${{ matrix.image }}-${{ matrix.target }}-${{ hashFiles('source/Cargo.toml.in', 'source/meson.build') }}
          restore-keys: |
            cargo-appimage-${{ matrix.image }}-${{ matrix.target }}-
            cargo-appimage-${{ matrix.image }}-

      - name: Compile AppImage
        id: appimageCompile
        run: |
          ./source/utils/buildAppImage.sh -d -i -s source -b appImageBuild | tee appImageBuildLog.txt

      - name: Upload AppImage Compile Log
        uses: actions/upload-artifact@v3
        if: ${{ (success() || steps.appimageCompile.outcome == 'failure') }}
        with:
          name: ${{ matrix.image }}-${{ github.sha }}-AppImageBuild-log
          path: ${{ github.workspace }}/appImageBuildLog.txt

  "Windows_Compile_Naev":
    needs: "Package_Source"

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: naev-windows
            config: windows_cross_mingw.ini
            target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.image }}
    steps:
      - name: Configure Build Environment
        run: |
          /usr/bin/setup-devenv.sh

      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: naev-dist-${{ github.sha }}

      - name: Extract Source
        run: |
          mkdir source
          tar -xf naev-*.tar.xz -C source --strip 1

      - name: Cache Meson wrap downloads
        uses: actions/cache@v3
        with:
          path: source/subprojects/packagecache
          key: wrap-${{ matrix.image }}-${{ hashFiles('source/subprojects/*.wrap') }}
          restore-keys: wrap-${{ matrix.image }}-

      - name: Cache Cargo home
        uses: actions/cache@v3
        with:
          path: build/cargo-home
          key: cargo-${{ matrix.image }}-${{ matrix.target }}-${{ hashFiles('source/Cargo.toml.in', 'source/meson.build') }}
          restore-keys: |
            cargo-${{ matrix.image }}-${{ matrix.target }}-
            cargo-${{ matrix.image }}-

      - name: Meson Setup
        id: setup
        run: |
          meson setup build source \
              --prefix="$(pwd)"/source/extras/windows/installer \
              --bindir=bin \
              -Dndata_path=bin \
              --cross-file='source/utils/build/${{ matrix.config }}' \
              --native-file='source/utils/build/linux.ini' \
              --buildtype=debug \
              --wrap-mode=nopromote \
              -Dinstaller=false \
              -Drelease=false \
              -Db_lto=false \
              -Dauto_features=enabled \
              -Ddocs_c=disabled \
              -Ddocs_lua=disabled

      - name: Upload Setup Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.setup.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}-${{ github.sha }}-setup-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

      - name: Meson Compile
        id: compile
        run: |
          meson compile -C build

      - name: Upload Compile Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.compile.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}-${{ github.sha }}-compile-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

      - name: Test Install
        id: install
        run: |
          meson install -C build

      - name: Upload Install Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.install.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}-${{ github.sha }}-install-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

  "Darwin_Compile_Naev":
    needs: "Package_Source"

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: naev-macos
            arch: x86_64
            config: macos_cross_osxcross.ini
          - image: naev-macos
            arch: aarch64
            config: macos_aarch64_cross_osxcross.ini

    runs-on: ${{ matrix.image }}
    env:
      BUILDARCH: "${{ matrix.arch }}"

    steps:
      - name: Configure Build Environment
        run: |
          /usr/bin/setup-devenv.sh

      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: naev-dist-${{ github.sha }}

      - name: Extract Source
        run: |
          mkdir source
          tar -xf naev-*.tar.xz -C source --strip 1

      - name: Cache Meson wrap downloads
        uses: actions/cache@v3
        with:
          path: source/subprojects/packagecache
          key: wrap-${{ matrix.image }}-${{ hashFiles('source/subprojects/*.wrap') }}
          restore-keys: wrap-${{ matrix.image }}-

      - name: Cache Cargo home
        uses: actions/cache@v3
        with:
          path: build/cargo-home
          key: cargo-${{ matrix.image }}-${{ matrix.arch }}-${{ hashFiles('source/Cargo.toml.in', 'source/meson.build') }}
          restore-keys: |
            cargo-${{ matrix.image }}-${{ matrix.arch }}-
            cargo-${{ matrix.image }}-

      - name: Meson Setup
        id: setup
        run: |
          meson setup build source \
              --prefix="$(pwd)"/build/dist/Naev.app \
              --bindir=Contents/MacOS \
              --libdir=Contents/Frameworks \
              -Dndata_path=Contents/Resources \
              --cross-file='source/utils/build/${{ matrix.config }}' \
              --native-file='source/utils/build/linux.ini' \
              --buildtype=debug \
              -Dinstaller=false \
              -Drelease=false \
              -Db_lto=false \
              -Dauto_features=enabled \
              -Ddocs_c=disabled \
              -Ddocs_lua=disabled


      - name: Upload Setup Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.setup.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}.${{ matrix.arch }}-${{ github.sha }}-setup-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

      - name: Meson Compile
        id: compile
        run: |
          meson compile -C build

      - name: Upload Compile Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.compile.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}.${{ matrix.arch }}-${{ github.sha }}-compile-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

      - name: Test Install
        id: install
        run: |
          meson install -C build

      - name: Upload Install Log
        uses: actions/upload-artifact@v3
        if: ${{ success() || steps.install.outcome == 'failure' }}
        with:
          name: ${{ matrix.image }}.${{ matrix.arch }}-${{ github.sha }}-install-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

  "Documentation":
    runs-on: naev-docs
    needs:
      [
        Linux_Compile_Naev,
        Windows_Compile_Naev,
        Darwin_Compile_Naev,
      ]

    steps:
      - name: Get Source
        uses: actions/download-artifact@v3
        with:
          name: naev-dist-${{ github.sha }}

      - name: Extract Source
        run: |
          mkdir source
          tar -xf naev-*.tar.xz -C source --strip 1

      - name: Meson Setup
        run: |
          meson setup build source \
              -Dexecutable=disabled

      - name: Meson Compile
        id: compile
        run: |
          meson compile -C build
          meson compile -C build manual

      - name: Upload Compile Log
        uses: actions/upload-artifact@v3
        if: ${{ steps.compile.outcome == 'failure' }}
        with:
          name: ${{ github.sha }}-ldoc-log
          path: ${{ github.workspace }}/build/meson-logs/meson-log.txt

      - name: Trigger Website Build
        if: ${{ steps.compile.outcome == 'success' && github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.WEBSITE_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            "https://codeberg.org/api/v1/repos/naev/naev-website/actions/workflows/api_build.yml/dispatches" \
            -d '{"ref": "main"}'
