name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  spellcheck:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        show-progress: false
    - uses: https://github.com/codespell-project/actions-codespell@v2
      with:
        path: dat/missions/, dat/events
        ignore_words_file: .codespellignore
