[package]
name = "physics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
naevc = { workspace = true }
anyhow = { workspace = true }
mlua = { workspace = true }
nalgebra = { workspace = true }
derive_more = { workspace = true }
static_assertions = { workspace = true }
encase = { workspace = true }
