--[[
-- @brief Generates pilot names
--]]
function pirate_name ()
   -- For translation, just transliterate if necessary. (Note the space
   -- appended to each entry; this can be omitted for transliterations
   -- to languages that don't use spaces, like Japanese.)
   local articles = {
      _("Das "),
      _("Der "),
      _("Kono "),
      _("Le "),
      _("The "),
      _("Ye "),
   }
   local descriptors = {
      _("Aerobic "),
      _("Amai "),
      _("Astro "),
      _("Baggy "),
      _("Bakana "),
      _("Bald "),
      _("Beautiful "),
      _("Big "),
      _("Bloody "),
      _("Brooding "),
      _("BT "),
      _("Clustered "),
      _("Creamy "),
      _("Crusty "),
      _("Dark "),
      _("Defiant "),
      _("Delicious "),
      _("Destructive "),
      _("Diligent "),
      _("Drunk "),
      _("Egotistical "),
      _("Eternal "),
      _("Evil "),
      _("Fearless "),
      _("Fearsome "),
      _("Filthy "),
      _("Flying "),
      _("Fuketeru "),
      _("Full-Motion "),
      _("Gigantic "),
      _("Glittery "),
      _("Groß"),
      _("Hashitteru "),
      _("Hen'na "),
      _("Horrible "),
      _("IDS "),
      _("Insatiable "),
      _("Kakkowarui "),
      _("Koronderu "),
      _("Kowai "),
      _("Lovely "),
      _("Lustful "),
      _("Malodorous "),
      _("Messy "),
      _("Mighty "),
      _("Mijikai "),
      _("Morbid "),
      _("Mukashi No "),
      _("Murderous "),
      _("Night's "),
      _("No Good "),
      _("Numb "),
      _("Oishī "),
      _("Ōkina "),
      _("Oyoideru "),
      _("Perilous "),
      _("Pirate's "),
      _("Pocket "),
      _("Psychic "),
      _("Relentless "),
      _("Rough "),
      _("Ruthless "),
      _("Saccharin "),
      _("Samui "),
      _("Satanic "),
      _("Slimy "),
      _("Smelly "),
      _("Space "),
      _("Strange "),
      _("Strawhat "),
      _("Sukina "),
      _("Takai "),
      _("Terrible "),
      _("Tired "),
      _("Toothless "),
      _("Tsukareteru "),
      _("Umai "),
      _("Undead "),
      _("Unhealthy "),
      _("Unsightly "),
      _("Utsukushī "),
      _("Vengeful "),
      _("Very Bad "),
      _("Warui "),
      _("Winged "),
      _("Wretched "),
      _("Yaseteru "),
      _("Yasui "),
      _("Yummy "),
   }
   local colours = {
      _("Akai "),
      _("Amarillo "),
      _("Aoi "),
      _("Azul "),
      _("Black "),
      _("Blau "),
      _("Bleu "),
      _("Blue "),
      _("Braun "),
      _("Brown "),
      _("Chairo No "),
      _("Crimson "),
      _("Cyan "),
      _("Gelb "),
      _("Green "),
      _("Grün "),
      _("Kiiroi "),
      _("Kuroi "),
      _("Mauve "),
      _("Purple "),
      _("Red "),
      _("Roho "),
      _("Schwarz "),
      _("Shiroi "),
      _("Yellow "),
   }
   local actors = {
      _("1024"),
      _("Aku"),
      _("Akuma"),
      _("Amigo"),
      _("Angle Grinder"),
      _("Anvil"),
      _("Axis"),
      _("Baka"),
      _("Bakemono"),
      _("Band Saw"),
      _("Bat"),
      _("Beard"),
      _("Belt Sander"),
      _("Bench Grinder"),
      _("Blargh"),
      _("Blunder"),
      _("Bobber"),
      _("Bolt Cutter"),
      _("Bōshi"),
      _("Box"),
      _("Bulk"),
      _("Cane"),
      _("Chainsaw"),
      _("Cheese"),
      _("Chi"),
      _("Circle"),
      _("Claw Hammer"),
      _("Corsair"),
      _("Crisis"),
      _("Crowbar"),
      _("Death"),
      _("Demon"),
      _("Destroyer"),
      _("Devil"),
      _("Donkey"),
      _("Doom"),
      _("Dragon"),
      _("Dread"),
      _("Drill Press"),
      _("Ego"),
      _("Emperor"),
      _("Gaki"),
      _("Gift"),
      _("Hamburger"),
      _("Horror"),
      _("Husband"),
      _("Ichigo"),
      _("Id"),
      _("Impact Wrench"),
      _("Inazuma"),
      _("Insanity"),
      _("Ishi"),
      _("Itoyōji"),
      _("Jalapeño"),
      _("Jigsaw"),
      _("Jishin"),
      _("Kaji"),
      _("Kamikaze"),
      _("Katana"),
      _("Keel"),
      _("Killer"),
      _("Kirin"),
      _("Kitsune"),
      _("Kōmori"),
      _("Lance"),
      _("Monster"),
      _("Mosquito"),
      _("Moustache"),
      _("Mugi"),
      _("Neckbeard"),
      _("Nezumi"),
      _("Niku"),
      _("Ninja"),
      _("Ogre"),
      _("Oni"),
      _("Oyster"),
      _("Paste"),
      _("Peril"),
      _("Pickaxe"),
      _("Pipe Wrench"),
      _("Pitchfork"),
      _("Potato"),
      _("Pride"),
      _("Raider"),
      _("Raigeki"),
      _("Rat"),
      _("Rubber Mallet"),
      _("Sakura"),
      _("Salad"),
      _("Sasori"),
      _("Scythe"),
      _("Sentinel"),
      _("Serpent"),
      _("Shinigami"),
      _("Shinobi"),
      _("Shujin"),
      _("Squeegee"),
      _("Staple Gun"),
      _("Stern"),
      _("Stir-fry"),
      _("Table Saw"),
      _("Tallman"),
      _("Tatsumaki"),
      _("Terror"),
      _("Thunder"),
      _("Tsuchi"),
      _("Tumbler"),
      _("Turret Lathe"),
      _("Tyrant"),
      _("Vengeance"),
      _("Wizard"),
      _("Yakuza"),
      _("Yarou"),
      _("Yatsu"),
      _("Youma"),
      _("Zombie"),
   }
   local article = articles[ rnd.rnd(1,#articles) ]
   local descriptor = descriptors[ rnd.rnd(1,#descriptors) ]
   local colour = colours[ rnd.rnd(1,#colours) ]
   local actor = actors[ rnd.rnd(1,#actors) ]

   local r = rnd.rnd()
   if r < 0.166 then
      return article .. actor
   elseif r < 0.333 then
      return colour .. actor
   elseif r < 0.50 then
      return descriptor .. actor
   elseif r < 0.666 then
      return article .. descriptor .. actor
   elseif r < 0.833 then
      return article .. colour .. actor
   else
      return article .. descriptor .. colour .. actor
   end
end
