-- THIS FILE IS AUTOMATICALLY GENERATED BY 'utils/docmaker'
-- ALL LOCAL CHANGES WILL BE LOST ON REGENERATION, SO DO NOT MODIFY PLEASE
local stds = {}
stds.ai = {
   read_globals = {
      ai = {
         fields = {
            pushtask = {},
            poptask = {},
            taskname = {},
            taskdata = {},
            pushsubtask = {},
            popsubtask = {},
            subtaskname = {},
            subtaskdata = {},
            pilot = {},
            rndpilot = {},
            nearestpilot = {},
            dist = {},
            dist2 = {},
            flyby_dist = {},
            minbrakedist = {},
            isbribed = {},
            instantJump = {},
            ismaxvel = {},
            isstopped = {},
            isenemy = {},
            isally = {},
            haslockon = {},
            hasprojectile = {},
            scandone = {},
            accel = {},
            turn = {},
            face = {},
            careful_face = {},
            aim = {},
            iface = {},
            dir = {},
            idir = {},
            drift_facing = {},
            brake = {},
            nearestlandspob = {},
            spobfrompos = {},
            rndspob = {},
            landspob = {},
            land = {},
            hyperspace = {},
            sethyptarget = {},
            nearhyptarget = {},
            rndhyptarget = {},
            canHyperspace = {},
            hyperspaceAbort = {},
            relvel = {},
            follow_accurate = {},
            face_accurate = {},
            stop = {},
            dock = {},
            combat = {},
            settarget = {},
            setasterotarget = {},
            getgatherable = {},
            gatherablepos = {},
            weapset = {},
            hascannons = {},
            hasturrets = {},
            hasfighterbays = {},
            hasafterburner = {},
            getenemy = {},
            hostile = {},
            getweaprangemin = {},
            getweaprange = {},
            getweapspeed = {},
            getweapammo = {},
            canboard = {},
            relsize = {},
            reldps = {},
            relhp = {},
            board = {},
            refuel = {},
            settimer = {},
            timeup = {},
            set_shoot_indicator = {},
            shoot_indicator = {},
            distress = {},
            getBoss = {},
            setcredits = {},
            messages = {},
            stealth = {},
            outfitOffAll = {},
         }
      }
   }
}
stds.audio = {
   read_globals = {
      audio = {
         fields = {
            __tostring = {},
            new = {},
            clone = {},
            play = {},
            isPlaying = {},
            pause = {},
            isPaused = {},
            stop = {},
            isStopped = {},
            rewind = {},
            seek = {},
            tell = {},
            getDuration = {},
            setVolume = {},
            getVolume = {},
            setRelative = {},
            isRelative = {},
            setPosition = {},
            getPosition = {},
            setVelocity = {},
            getVelocity = {},
            setLooping = {},
            setLooping = {},
            isLooping = {},
            setPitch = {},
            getPitch = {},
            setAttenuationDistances = {},
            getAttenuationDistances = {},
            setRolloff = {},
            getRolloff = {},
            setEffect = {},
            setEffectData = {},
            setGlobalEffect = {},
            setSpeedOfSound = {},
            setAirAbsorption = {},
            setDopplerFactor = {},
         }
      }
   }
}
stds.audiodata = {
   read_globals = {
      audiodata = {
         fields = {
            __tostring = {},
            new = {},
            getDuration = {},
            getChannels = {},
            getSampleCount = {},
            getSampleRate = {},
         }
      }
   }
}
stds.data = {
   read_globals = {
      data = {
         fields = {
            new = {},
            get = {},
            set = {},
            getSize = {},
         }
      }
   }
}
stds.file = {
   read_globals = {
      file = {
         fields = {
            from_string = {},
            new = {},
            open = {},
            close = {},
            read = {},
            write = {},
            seek = {},
            getFilename = {},
            getMode = {},
            getSize = {},
            isOpen = {},
            filetype = {},
            mkdir = {},
            enumerate = {},
            remove = {},
         }
      }
   }
}
stds.asteroid = {
   read_globals = {
      asteroid = {
         fields = {
            __eq = {},
            __tostring = {},
            getAll = {},
            get = {},
            exists = {},
            state = {},
            setState = {},
            field = {},
            pos = {},
            vel = {},
            setPos = {},
            setVel = {},
            scanned = {},
            timer = {},
            setTimer = {},
            armour = {},
            setArmour = {},
            alertRange = {},
            materials = {},
         }
      }
   }
}
stds.bkg = {
   read_globals = {
      bkg = {
         fields = {
            clear = {},
            image = {},
         }
      }
   }
}
stds.camera = {
   read_globals = {
      camera = {
         fields = {
            set = {},
            get = {},
            pos = {},
            setZoom = {},
            getZoom = {},
            shake = {},
         }
      }
   }
}
stds.canvas = {
   read_globals = {
      canvas = {
         fields = {
            __gc = {},
            __eq = {},
            new = {},
            set = {},
            dims = {},
            getTex = {},
            clear = {},
         }
      }
   }
}
stds.commodity = {
   read_globals = {
      commodity = {
         fields = {
            __eq = {},
            get = {},
            getStandard = {},
            flags = {},
            name = {},
            nameRaw = {},
            price = {},
            priceAt = {},
            priceAtTime = {},
            canSell = {},
            canBuy = {},
            icon = {},
            description = {},
            new = {},
            illegalto = {},
            illegality = {},
            tags = {},
         }
      }
   }
}
stds.diff = {
   read_globals = {
      diff = {
         fields = {
            apply = {},
            remove = {},
            isApplied = {},
         }
      }
   }
}
stds.evt = {
   read_globals = {
      evt = {
         fields = {
            npcAdd = {},
            npcRm = {},
            finish = {},
            save = {},
            claim = {},
         }
      }
   }
}
stds.faction = {
   read_globals = {
      faction = {
         fields = {
            exists = {},
            get = {},
            getAll = {},
            player = {},
            __eq = {},
            name = {},
            nameRaw = {},
            longname = {},
            areNeutral = {},
            areEnemies = {},
            areAllies = {},
            hit = {},
            hitTest = {},
            reputationGlobal = {},
            reputationText = {},
            reputationDefault = {},
            setReputationGlobal = {},
            applyLocalThreshold = {},
            enemies = {},
            allies = {},
            usesHiddenJumps = {},
            logo = {},
            colour = {},
            known = {},
            setKnown = {},
            invisible = {},
            static = {},
            reputationOverride = {},
            setReputationOverride = {},
            tags = {},
            dynAdd = {},
            dynAlly = {},
            dynEnemy = {},
         }
      }
   }
}
stds.font = {
   read_globals = {
      font = {
         fields = {
            __gc = {},
            __eq = {},
            new = {},
            height = {},
            width = {},
            setFilter = {},
            addFallback = {},
         }
      }
   }
}
stds.gfx = {
   read_globals = {
      gfx = {
         fields = {
            dim = {},
            screencoords = {},
            renderTex = {},
            renderTexRaw = {},
            renderTexH = {},
            renderRect = {},
            renderRectH = {},
            renderCircle = {},
            renderCircleH = {},
            renderLinesH = {},
            clearDepth = {},
            fontSize = {},
            printDim = {},
            printfDim = {},
            printfEnd = {},
            printfWrap = {},
            printRestoreClear = {},
            printRestoreLast = {},
            printf = {},
            printH = {},
            print = {},
            printText = {},
            setBlendMode = {},
            setBlendState = {},
            setScissor = {},
            screenshot = {},
            lightAmbient = {},
            lightAmbientGet = {},
            lightIntensity = {},
            lightIntensityGet = {},
            glVersion = {},
         }
      }
   }
}
stds.gui = {
   read_globals = {
      gui = {
         fields = {
            viewport = {},
            fpsPos = {},
            osdInit = {},
            mesgInit = {},
            omsgInit = {},
            radarInit = {},
            radarRender = {},
            targetSpobGFX = {},
            targetPilotGFX = {},
            mouseClickEnable = {},
            mouseMoveEnable = {},
            setMapOverlayBounds = {},
            cameraOffset = {},
         }
      }
   }
}
stds.hook = {
   read_globals = {
      hook = {
         fields = {
            rm = {},
            land = {},
            info = {},
            load = {},
            takeoff = {},
            jumpout = {},
            jumpin = {},
            enter = {},
            hail_spob = {},
            hail = {},
            board = {},
            timer = {},
            timerClear = {},
            date = {},
            comm_buy = {},
            comm_sell = {},
            comm_jettison = {},
            gather = {},
            outfit_buy = {},
            outfit_sell = {},
            equip = {},
            ship_buy = {},
            ship_sell = {},
            ship_swap = {},
            input = {},
            mouse = {},
            standing = {},
            discover = {},
            asteroid_scan = {},
            pay = {},
            safe = {},
            update = {},
            renderbg = {},
            renderfg = {},
            rendertop = {},
            mission_done = {},
            event_done = {},
            custom = {},
            pilot = {},
         }
      }
   }
}
stds.jump = {
   read_globals = {
      jump = {
         fields = {
            get = {},
            __eq = {},
            __tostring = {},
            reverse = {},
            radius = {},
            pos = {},
            hide = {},
            angle = {},
            hidden = {},
            exitonly = {},
            system = {},
            dest = {},
            jumpDist = {},
            known = {},
            setKnown = {},
         }
      }
   }
}
stds.linopt = {
   read_globals = {
      linopt = {
         fields = {
            __gc = {},
            __eq = {},
            new = {},
            size = {},
            add_cols = {},
            add_rows = {},
            set_col = {},
            set_row = {},
            load_matrix = {},
            solve = {},
            read_problem = {},
            write_problem = {},
         }
      }
   }
}
stds.misn = {
   read_globals = {
      misn = {
         fields = {
            setTitle = {},
            setDesc = {},
            setReward = {},
            setDistance = {},
            setIllegal = {},
            setFaction = {},
            markerAdd = {},
            markerMove = {},
            markerRm = {},
            setNPC = {},
            factions = {},
            accept = {},
            finish = {},
            cargoAdd = {},
            cargoRm = {},
            cargoJet = {},
            osdHide = {},
            osdSetHide = {},
            osdCreate = {},
            osdDestroy = {},
            osdActive = {},
            osdGetActive = {},
            osdGet = {},
            npcAdd = {},
            npcRm = {},
            claim = {},
            computerRefresh = {},
         }
      }
   }
}
stds.munition = {
   read_globals = {
      munition = {
         fields = {
            __eq = {},
            __tostring = {},
            exists = {},
            clear = {},
            getAll = {},
            getInrange = {},
            pos = {},
            vel = {},
            faction = {},
            parent = {},
            target = {},
            outfit = {},
            strength = {},
            strengthSet = {},
         }
      }
   }
}
stds.music = {
   read_globals = {
      music = {
         fields = {
            choose = {},
            play = {},
            pause = {},
            stop = {},
            isPlaying = {},
            current = {},
            getVolume = {},
         }
      }
   }
}
stds.naev = {
   read_globals = {
      naev = {
         fields = {
            version = {},
            versionTest = {},
            language = {},
            lastplayed = {},
            date = {},
            ticksGame = {},
            ticks = {},
            clock = {},
            fps = {},
            keyGet = {},
            keyEnable = {},
            keyEnableAll = {},
            keyDisableAll = {},
            eventStart = {},
            missionList = {},
            missionStart = {},
            missionTest = {},
            eventReload = {},
            missionReload = {},
            shadersReload = {},
            isSimulation = {},
            conf = {},
            confSet = {},
            cache = {},
            trigger = {},
            claimTest = {},
            plugins = {},
            menuInfo = {},
            menuSmall = {},
            isPaused = {},
            pause = {},
            unpause = {},
            hasTextInput = {},
            setTextInput = {},
            shipstats = {},
            unit = {},
            quadtreeParams = {},
            difficulty = {},
            difficultyLevel = {},
            supported_image_ext = {},
            debugTrails = {},
            debugCollisions = {},
         }
      }
   }
}
stds.news = {
   read_globals = {
      news = {
         fields = {
            add = {},
            rm = {},
            get = {},
            __eq = {},
            title = {},
            desc = {},
            faction = {},
            date = {},
            bind = {},
         }
      }
   }
}
stds.outfit = {
   read_globals = {
      outfit = {
         fields = {
            __eq = {},
            get = {},
            exists = {},
            getAll = {},
            name = {},
            nameRaw = {},
            shortname = {},
            type = {},
            typeBroad = {},
            cpu = {},
            mass = {},
            slot = {},
            slotExtra = {},
            limit = {},
            icon = {},
            license = {},
            price = {},
            description = {},
            summary = {},
            unique = {},
            friendlyfire = {},
            pointdefense = {},
            missShips = {},
            missAsteroids = {},
            toggleable = {},
            shipstat = {},
            weapstats = {},
            specificstats = {},
            illegality = {},
            tags = {},
         }
      }
   }
}
stds.pilot = {
   read_globals = {
      pilot = {
         fields = {
            choosePoint = {},
            add = {},
            clone = {},
            rm = {},
            explode = {},
            clearSelect = {},
            clear = {},
            canSpawn = {},
            toggleSpawn = {},
            get = {},
            getAllies = {},
            getEnemies = {},
            getVisible = {},
            getInrange = {},
            __eq = {},
            __tostring = {},
            name = {},
            id = {},
            exists = {},
            target = {},
            setTarget = {},
            targetAsteroid = {},
            setTargetAsteroid = {},
            inrange = {},
            scandone = {},
            withPlayer = {},
            nav = {},
            navSpob = {},
            navSpobSet = {},
            navJump = {},
            navJumpSet = {},
            autoweap = {},
            weapset = {},
            weapsetList = {},
            weapsetType = {},
            weapsetAdd = {},
            weapsetAddType = {},
            weapsetRm = {},
            weapsetCleanup = {},
            weapsetSetInrange = {},
            weapsetAmmo = {},
            weapsetAuto = {},
            actives = {},
            outfitsList = {},
            outfits = {},
            outfitsEquip = {},
            outfitGet = {},
            outfitToggle = {},
            outfitReady = {},
            rename = {},
            pos = {},
            vel = {},
            isStopped = {},
            signature = {},
            stealthRange = {},
            dir = {},
            mass = {},
            accel = {},
            speed = {},
            speedMax = {},
            turn = {},
            faction = {},
            reputation = {},
            areEnemies = {},
            areAllies = {},
            spaceworthy = {},
            setPos = {},
            setVel = {},
            setDir = {},
            broadcast = {},
            comm = {},
            setFaction = {},
            setHostile = {},
            setFriendly = {},
            setInvincible = {},
            setInvincPlayer = {},
            setHide = {},
            setInvisible = {},
            setNoRender = {},
            setVisplayer = {},
            setVisible = {},
            setHilight = {},
            setBribed = {},
            setActiveBoard = {},
            disabled = {},
            setNoDeath = {},
            setDisable = {},
            cooldown = {},
            setCooldown = {},
            cooldownCycle = {},
            setNoJump = {},
            setNoLand = {},
            setNoClear = {},
            outfitHasSlot = {},
            outfitAdd = {},
            outfitSlot = {},
            outfitAddSlot = {},
            outfitRm = {},
            outfitRmSlot = {},
            outfitInitSlot = {},
            outfitMessageSlot = {},
            outfitAddIntrinsic = {},
            outfitRmIntrinsic = {},
            outfitsReset = {},
            fuel = {},
            setFuel = {},
            intrinsicReset = {},
            intrinsicSet = {},
            intrinsicGet = {},
            shippropReset = {},
            shippropSet = {},
            shippropGet = {},
            effectClear = {},
            effectAdd = {},
            effectRm = {},
            effectHas = {},
            effects = {},
            ai = {},
            changeAI = {},
            setHealth = {},
            setHealthAbs = {},
            addHealth = {},
            setEnergy = {},
            addEnergy = {},
            fillAmmo = {},
            setNoBoard = {},
            setNoDisable = {},
            setSpeedLimit = {},
            health = {},
            armour = {},
            shield = {},
            stress = {},
            energy = {},
            lockon = {},
            jamLockons = {},
            stats = {},
            shipstat = {},
            detectedDistance = {},
            cargoFree = {},
            cargoHas = {},
            cargoAdd = {},
            cargoRm = {},
            cargoJet = {},
            cargoList = {},
            credits = {},
            worth = {},
            colour = {},
            colourChar = {},
            hostile = {},
            flags = {},
            hasIllegal = {},
            ship = {},
            radius = {},
            points = {},
            idle = {},
            control = {},
            memory = {},
            shipMemory = {},
            ainame = {},
            task = {},
            taskname = {},
            taskstack = {},
            taskdata = {},
            taskClear = {},
            pushtask = {},
            poptask = {},
            refuel = {},
            moveto = {},
            face = {},
            brake = {},
            follow = {},
            attack = {},
            board = {},
            runaway = {},
            gather = {},
            canHyperspace = {},
            hyperspace = {},
            stealth = {},
            tryStealth = {},
            destealth = {},
            land = {},
            hailPlayer = {},
            msg = {},
            mothership = {},
            dockslot = {},
            leader = {},
            setLeader = {},
            followers = {},
            hookClear = {},
            collisionTest = {},
            damage = {},
            invincible = {},
            kill = {},
            knockback = {},
            distress = {},
            calcStats = {},
            shipvarPeek = {},
            shipvarPush = {},
            shipvarPop = {},
            render = {},
            renderTo = {},
         }
      }
   }
}
stds.pilotoutfit = {
   read_globals = {
      pilotoutfit = {
         fields = {
            id = {},
            slot = {},
            outfit = {},
            state = {},
            progress = {},
            set = {},
            clear = {},
            munition = {},
            shoot = {},
            mount = {},
         }
      }
   }
}
stds.player = {
   read_globals = {
      player = {
         fields = {
            name = {},
            ship = {},
            pay = {},
            credits = {},
            wealth = {},
            msg = {},
            msgClear = {},
            msgToggle = {},
            omsgAdd = {},
            omsgChange = {},
            omsgRm = {},
            allowSave = {},
            pos = {},
            pilot = {},
            jumps = {},
            fuel = {},
            refuel = {},
            autonav = {},
            autonavSetSpeed = {},
            autonavSetTarget = {},
            autonavSetPos = {},
            autonavDest = {},
            autonavRoute = {},
            autonavAbort = {},
            autonavReset = {},
            autonavEnd = {},
            dt_default = {},
            speed = {},
            setSpeed = {},
            cinematics = {},
            cinematicsCheck = {},
            damageSPFX = {},
            screenshot = {},
            tryBoard = {},
            unboard = {},
            isLanded = {},
            takeoff = {},
            tryLand = {},
            land = {},
            landAllow = {},
            landWindow = {},
            merchantOutfitName = {},
            commOpen = {},
            commClose = {},
            shipvarPeek = {},
            shipvarPush = {},
            shipvarPop = {},
            ships = {},
            shipOutfits = {},
            shipMetadata = {},
            shipDeploy = {},
            outfits = {},
            outfitNum = {},
            outfitAdd = {},
            outfitRm = {},
            shipAdd = {},
            shipSwap = {},
            missions = {},
            misnActive = {},
            misnDone = {},
            misnDoneList = {},
            evtActive = {},
            evtDone = {},
            evtDoneList = {},
            gui = {},
            guiList = {},
            guiSet = {},
            fleetList = {},
            fleetCargoFree = {},
            fleetCargoMissionFree = {},
            fleetCargoUsed = {},
            fleetCargoOwned = {},
            fleetCargoAdd = {},
            fleetCargoRm = {},
            fleetCargoJet = {},
            fleetCargoList = {},
            inventory = {},
            inventoryAdd = {},
            inventoryRm = {},
            inventoryOwned = {},
            hasLicence = {},
            teleport = {},
            dt_mod = {},
            fleetCapacity = {},
            fleetCapacitySet = {},
            chapter = {},
            chapterSet = {},
            infoButtonRegister = {},
            infoButtonUnregister = {},
            canDiscover = {},
            save = {},
            saveBackup = {},
            gameover = {},
            start = {},
         }
      }
   }
}
stds.safelanes = {
   read_globals = {
      safelanes = {
         fields = {
            get = {},
         }
      }
   }
}
stds.shader = {
   read_globals = {
      shader = {
         fields = {
            __gc = {},
            __eq = {},
            new = {},
            send = {},
            sendRaw = {},
            hasUniform = {},
            addPPShader = {},
            rmPPShader = {},
         }
      }
   }
}
stds.ship = {
   read_globals = {
      ship = {
         fields = {
            __eq = {},
            get = {},
            getAll = {},
            name = {},
            nameRaw = {},
            baseType = {},
            inherits = {},
            class = {},
            classDisplay = {},
            faction = {},
            fabricator = {},
            crew = {},
            mass = {},
            armour = {},
            cargo = {},
            fuelConsumption = {},
            licence = {},
            points = {},
            slots = {},
            getSlots = {},
            fitsSlot = {},
            cpu = {},
            price = {},
            time_mod = {},
            size = {},
            gfxPath = {},
            gfxComm = {},
            gfxStore = {},
            gfx = {},
            dims = {},
            screenSize = {},
            description = {},
            shipstat = {},
            shipstatDesc = {},
            tags = {},
            render = {},
         }
      }
   }
}
stds.shiplog = {
   read_globals = {
      shiplog = {
         fields = {
            create = {},
            append = {},
         }
      }
   }
}
stds.spob = {
   read_globals = {
      spob = {
         fields = {
            cur = {},
            exists = {},
            get = {},
            getS = {},
            getLandable = {},
            getAll = {},
            system = {},
            __eq = {},
            name = {},
            nameRaw = {},
            population = {},
            radius = {},
            faction = {},
            reputation = {},
            colour = {},
            colourChar = {},
            class = {},
            classLong = {},
            services = {},
            flags = {},
            canLand = {},
            landAllow = {},
            landDeny = {},
            getLandAllow = {},
            getLandDeny = {},
            pos = {},
            gfxSpace = {},
            gfxExterior = {},
            gfxExteriorPath = {},
            gfxComm = {},
            shipsSold = {},
            outfitsSold = {},
            commoditiesSold = {},
            blackmarket = {},
            known = {},
            setKnown = {},
            hostile = {},
            setHostile = {},
            recordCommodityPriceAtTime = {},
            tags = {},
         }
      }
   }
}
stds.system = {
   read_globals = {
      system = {
         fields = {
            cur = {},
            get = {},
            getAll = {},
            __eq = {},
            name = {},
            pos = {},
            nameRaw = {},
            faction = {},
            background = {},
            nebula = {},
            interference = {},
            jumpDist = {},
            jumpPath = {},
            adjacentSystems = {},
            jumps = {},
            asteroidFields = {},
            addGatherable = {},
            presences = {},
            spobs = {},
            presence = {},
            radius = {},
            known = {},
            setKnown = {},
            hidden = {},
            setHidden = {},
            markerClear = {},
            markerAdd = {},
            markerRm = {},
            reputation = {},
            setReputation = {},
            waypoints = {},
            tags = {},
         }
      }
   }
}
stds.time = {
   read_globals = {
      time = {
         fields = {
            new = {},
            add = {},
            sub = {},
            __eq = {},
            __lt = {},
            __le = {},
            get = {},
            str = {},
            inc = {},
            tonumber = {},
            fromnumber = {},
         }
      }
   }
}
stds.tk = {
   read_globals = {
      tk = {
         fields = {
            isOpen = {},
            query = {},
            msg = {},
            yesno = {},
            input = {},
            choice = {},
            list = {},
            merchantOutfit = {},
            custom = {},
            customRename = {},
            customFullscreen = {},
            customResize = {},
            customSize = {},
            customDone = {},
            refresh = {},
         }
      }
   }
}
stds.var = {
   read_globals = {
      var = {
         fields = {
            peek = {},
            pop = {},
            push = {},
         }
      }
   }
}
stds.transform = {
   read_globals = {
      transform = {
         fields = {
            new = {},
            __tostring = {},
            __mul = {},
            get = {},
            set = {},
            scale = {},
            translate = {},
            rotate2d = {},
            ortho = {},
            applyPoint = {},
            applyDim = {},
         }
      }
   }
}
stds.vec2 = {
   read_globals = {
      vec2 = {
         fields = {
            new = {},
            newP = {},
            clone = {},
            __tostring = {},
            add = {},
            sub = {},
            mul = {},
            div = {},
            dot = {},
            cross = {},
            get = {},
            polar = {},
            set = {},
            setP = {},
            dist = {},
            dist2 = {},
            mod = {},
            angle = {},
            normalize = {},
            collideLineLine = {},
            collideCircleLine = {},
         }
      }
   }
}
stds.colour = {
   read_globals = {
      colour = {
         fields = {
            __tostring = {},
            __eq = {},
            new = {},
            new_named = {},
            new_hsv = {},
            clone = {},
            alpha = {},
            rgb = {},
            rgba = {},
            hsv = {},
            rgb_to_hsv = {},
            hsv_to_rgb = {},
            set_rgb = {},
            set_hsv = {},
            set_alpha = {},
            to_gamma = {},
            to_linear = {},
         }
      }
   }
}
stds.tex = {
   read_globals = {
      tex = {
         fields = {
            __tostring = {},
            new = {},
            dim = {},
            sprites = {},
            spriteFromDir = {},
            setFilter = {},
            setWrap = {},
            draw = {},
            draw_ex = {},
            w = {},
            h = {},
         }
      }
   }
}
stds.rnd = {
   read_globals = {
      rnd = {
         fields = {
            rnd = {},
            sigma = {},
            twosigma = {},
            threesigma = {},
            uniform = {},
            angle = {},
            permutation = {},
         }
      }
   }
}
stds.spfx = {
   read_globals = {
      spfx = {
         fields = {
            new = {},
            rm = {},
            pos = {},
            setVel = {},
            setPos = {},
            setVel = {},
            sfx = {},
            data = {},
            debris = {},
            nebulaColour = {},
         }
      }
   }
}
stds.naev.read_globals.naev.fields.ai = stds.ai.read_globals.ai
stds.naev.read_globals.naev.fields.audio = stds.audio.read_globals.audio
stds.naev.read_globals.naev.fields.audiodata = stds.audiodata.read_globals.audiodata
stds.naev.read_globals.naev.fields.data = stds.data.read_globals.data
stds.naev.read_globals.naev.fields.file = stds.file.read_globals.file
stds.naev.read_globals.naev.fields.asteroid = stds.asteroid.read_globals.asteroid
stds.naev.read_globals.naev.fields.bkg = stds.bkg.read_globals.bkg
stds.naev.read_globals.naev.fields.camera = stds.camera.read_globals.camera
stds.naev.read_globals.naev.fields.canvas = stds.canvas.read_globals.canvas
stds.naev.read_globals.naev.fields.commodity = stds.commodity.read_globals.commodity
stds.naev.read_globals.naev.fields.diff = stds.diff.read_globals.diff
stds.naev.read_globals.naev.fields.evt = stds.evt.read_globals.evt
stds.naev.read_globals.naev.fields.faction = stds.faction.read_globals.faction
stds.naev.read_globals.naev.fields.font = stds.font.read_globals.font
stds.naev.read_globals.naev.fields.gfx = stds.gfx.read_globals.gfx
stds.naev.read_globals.naev.fields.gui = stds.gui.read_globals.gui
stds.naev.read_globals.naev.fields.hook = stds.hook.read_globals.hook
stds.naev.read_globals.naev.fields.jump = stds.jump.read_globals.jump
stds.naev.read_globals.naev.fields.linopt = stds.linopt.read_globals.linopt
stds.naev.read_globals.naev.fields.misn = stds.misn.read_globals.misn
stds.naev.read_globals.naev.fields.munition = stds.munition.read_globals.munition
stds.naev.read_globals.naev.fields.music = stds.music.read_globals.music
stds.naev.read_globals.naev.fields.news = stds.news.read_globals.news
stds.naev.read_globals.naev.fields.outfit = stds.outfit.read_globals.outfit
stds.naev.read_globals.naev.fields.pilot = stds.pilot.read_globals.pilot
stds.naev.read_globals.naev.fields.pilotoutfit = stds.pilotoutfit.read_globals.pilotoutfit
stds.naev.read_globals.naev.fields.player = stds.player.read_globals.player
stds.naev.read_globals.naev.fields.safelanes = stds.safelanes.read_globals.safelanes
stds.naev.read_globals.naev.fields.shader = stds.shader.read_globals.shader
stds.naev.read_globals.naev.fields.ship = stds.ship.read_globals.ship
stds.naev.read_globals.naev.fields.shiplog = stds.shiplog.read_globals.shiplog
stds.naev.read_globals.naev.fields.spob = stds.spob.read_globals.spob
stds.naev.read_globals.naev.fields.system = stds.system.read_globals.system
stds.naev.read_globals.naev.fields.time = stds.time.read_globals.time
stds.naev.read_globals.naev.fields.tk = stds.tk.read_globals.tk
stds.naev.read_globals.naev.fields.var = stds.var.read_globals.var
stds.naev.read_globals.naev.fields.transform = stds.transform.read_globals.transform
stds.naev.read_globals.naev.fields.vec2 = stds.vec2.read_globals.vec2
stds.naev.read_globals.naev.fields.colour = stds.colour.read_globals.colour
stds.naev.read_globals.naev.fields.tex = stds.tex.read_globals.tex
stds.naev.read_globals.naev.fields.rnd = stds.rnd.read_globals.rnd
stds.naev.read_globals.naev.fields.spfx = stds.spfx.read_globals.spfx
return stds
