#!/bin/bash


if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ -z "$*" ] ; then
   DOC=(
      "usage  $(basename "$0") [-d <subst_dic.txt>] <file>.."
      "  Apply the en->en-Oxford (or <subst_dic.txt> if specified) substitution list to each <file>."
      "  <subst_dic.txt> is a list of lines in the form '.*->.*'."
      "  In particular, codespell dictionaries are valid."
      "  So far, substitutions are only suggested."
   )
   ( IFS=$'\n'; echo "${DOC[*]}" ) >&2
   exit 0
fi

if [ "$1" = '-d' ] ; then
   shift
   DIC="$1"
   shift
else
   DIC="$( dirname -- "${BASH_SOURCE[0]}" )"/dictionary_en_to_en-OX_AUTOGENERATED.txt
fi

if [ -z "$*" ] ; then
   echo "args expected. Try $(basename "$0") -h" >&2
   exit 1
fi

match_list() {
   WL="$*"
   echo '\(^\|[^:."]\|\([^a-zA-Z)][.:]\)\)\<\(\('"${WL// /\\)\\|\\(}"'\)\)\>\($\|[^:."(]\|\([.:(][^a-zA-Z]\)\)'
}

readarray -t WORDS <<< "$(sed "s/\(·\)*->\(.*\)$/\1/" "$DIC")"
EXPR="$(match_list "${WORDS[@]}")"

readarray -t FILES <<< "$( grep -l "$EXPR" "$@" )"

if [ -z "${FILES[*]}" ] ; then
   exit 0
fi

readarray -t WORDS <<< "$(
   grep -h -o "$EXPR" "${FILES[@]}" |
   sed 's/^\(.\?[^a-zA-Z]\)\?\([a-zA-Z]*\)[^a-zA-Z]\?.\?$/\2/' |
   sort -u
)"

EXPR="$(match_list "${WORDS[@]}")"

WL="${WORDS[*]}"
SUBDIC="$(grep -f - "$DIC" <<< "^${WL// /->$'\n'^}->")"

MARK="01;31"
E=$'\e'

grep --color=always -n "$EXPR" "${FILES[@]}"                                                 |
sed "s/$E\[K//g"                                                                             |
sed "s/\($E\[${MARK}m\)\(.\?[^a-zA-Z]\)\?\([a-zA-Z]*\)\([^a-zA-Z]*\)\($E\[m\)/\2\1\3\5\4/g"  |
sed -f <(
   sed "s/^\(.*\)->\(.*\)/s\/\\\($E\\\[${MARK}m\1$E\\\[m\\\)\/\\\1$E\\\[1;33m->$E\\\[0;32m\2$E\\\[m\/g;/" <<< "$SUBDIC"
)
