source 'https://rubygems.org'

gem 'nanoc', '>=4.0'
group :nanoc do
  gem 'nanoc-javascript-concatenator'
  gem 'nanoc-external'
  gem 'nanoc-dart-sass'
end

gem 'webrick'
gem 'packr'
gem 'kramdown'
gem 'nokogiri'
gem 'nokogiri-pretty'
gem 'rainpress'
gem 'image_size'
gem 'pygments.rb'
gem 'builder'
gem 'uglifier'
gem 'mini_racer'
gem 'activesupport'
gem 'typogruby'
gem 'terser'
gem 'adsf'

gem 'w3c_validators'
