name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: eine/setup-msys2@v1
      with:
        update: true
        install: |
          mingw-w64-x86_64-libtool
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_mixer
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-libpng
          mingw-w64-x86_64-openal
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-freetype
          mingw-w64-x86_64-libzip
          mingw-w64-x86_64-gettext
          mingw-w64-x86_64-luajit
          libtool
          autoconf
          automake
          automake-wrapper
          git
          gettext
          pkgconfig
          make
          intltool
          
    - uses: actions/checkout@v2
    - run: |
        ./autogen.sh
        ./configure
        make -j$(nproc --all)
