name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: eine/setup-msys2@v1
      with:
        update: true
        install: base-devel git
    - uses: actions/checkout@v2
    - run: git --version
